name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting:
    name: Formatting
    uses: sapphiredev/.github/.github/workflows/reusable-prettier.yml@main

  linting:
    name: Linting
    uses: sapphiredev/.github/.github/workflows/reusable-lint.yml@main

  typecheck:
    name: Typecheck
    uses: sapphiredev/.github/.github/workflows/reusable-typecheck.yml@main

  sonar:
    name: Sonar Analysis
    uses: sapphiredev/.github/.github/workflows/reusable-sonar.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
