name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Formatting:
    name: Checking formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Use Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.yarnpkg.com/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Check formatting
        run: yarn format:check
